# -*- coding: utf-8 -*-
"""PROJECT 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R5Gfwq6fqUpBh6-9fCFE4zpYEvM3M6YT
"""

# Calculating the student's marks
Name=input("Enter your name: ") #Input=Name
Grade=input("Enter yuor grade: ")#Input=Grade
Sub=int(input("Enter the number of Subjects (5/6): "))# Input= Number of Subject
English=float(input("Enter your marks in English: "))#Input= Marks in English
Tamil=float(input("Enter your marks in Tamil: "))#Input=Marks in Tamil
Science=float(input("Enter your marks in Science: "))#Input= Marks in Science
Social=float(input("Enter your marks in Social: "))#Input= Marks in Social
Maths=float(input("Enter your marks in Maths: "))#Input= Marks in Maths
if Sub==6:#If the statement is true then execute the following code
   Hindi=float(input("Enter your marks in Hindi: "))#Input=Marks in Hindi
   Total=English+Tamil+Science+Social+Maths+Hindi#Calculating the total including Hindi
   Average=Total/6 #Calculating the Average including Hindi
   Average=round(Average,2)#Rounding the decimal digits to 2
   print(f"Your total mark is {Total}")#Displaying the Total marks including Hindi
   print(f"Your average mark is {Average} ")#Displaying the Average marks including Hindi
else:#If it is flase execute the following code
   Total=English+Tamil+Science+Social+Maths#Calculating the total excluding Hindi
   Average=Total/5 #Calculating the Average excluding Hindi
   Average=round(Average,2)#Rounding the decimal digits to 2
   print(f"Your total mark is {Total}")#Displaying the Total marks excluding Hindi
   print(f"Your average mark is {Average} ")#Displaying the Average marks excluding Hindi


#    inputs and outputs:

# (i) Enter your name: Akshaya Vivekha
#     Enter yuor grade: VII
#     Enter the number of Subjects (5/6): 6
#     Enter your marks in English: 98
#     Enter your marks in Tamil: 99
#     Enter your marks in Science: 96
#     Enter your marks in Social: 99
#     Enter your marks in Maths: 98
#     Enter your marks in Hindi: 100
#     Your total mark is 590.0
#     Your average mark is 98.33

#  (ii) Enter your name: Hema
#       Enter yuor grade: X
#       Enter the number of Subjects (5/6): 5
#       Enter your marks in English: 99
#       Enter your marks in Tamil: 98
#       Enter your marks in Science: 100
#       Enter your marks in Social: 99
#       Enter your marks in Maths: 100
#       Your total mark is 496.0
#       Your average mark is 99.2